"""LLM client with streaming support."""
from __future__ import annotations

import json
import logging
import time
from typing import Any, Dict, Generator, Optional, Tuple
import urllib.request
import urllib.error

logger = logging.getLogger(__name__)


class LLMClient:
    """Client for LLM API with streaming support."""
    
    def __init__(self, config: Dict[str, Any] = None):
        self.config = config or {}
        self.model = self.config.get("model", "gpt-3.5-turbo")
        self.api_key = self.config.get("api_key", "")
        self.base_url = self.config.get("base_url", "https://api.openai.com/v1")
        self.timeout = self.config.get("timeout", 30)
        self.max_retries = self.config.get("max_retries", 3)
        
    def query_llm(self, prompt: str, **kwargs) -> Dict[str, Any]:
        """
        Query LLM synchronously.
        
        Returns:
            Dict with response, trust_score, etc.
        """
        # This is a simplified version for backward compatibility
        # In production, this would call the actual LLM API
        return {
            "response": f"Response to: {prompt[:50]}...",
            "trust_score": 0.95,
            "reasoning": "Generated by LLM",
            "usage": {"total_tokens": 100},
            "finish_reason": "stop"
        }
    
    def stream_llm_response(self, prompt: str, **kwargs) -> Generator[str, None, None]:
        """
        Stream LLM response token by token.
        
        Yields:
            str: Each token/chunk of the response
            
        Note:
            This is a mock implementation for demonstration.
            In production, this would connect to actual LLM API with streaming.
        """
        # Mock response for demonstration
        mock_response = (
            f"Это stream-ответ от LLM на запрос: {prompt[:50]}... "
            "Ответ генерируется постепенно, токен за токеном. "
            "Streaming улучшает UX при длинных ответах. "
            "Оператор видит прогресс генерации в реальном времени. "
            "Это особенно полезно для сложных запросов. "
            "[Trust Score: 0.95]"
        )
        
        # Split into chunks to simulate token streaming
        words = mock_response.split()
        for i, word in enumerate(words):
            # Simulate token generation delay
            time.sleep(0.05)
            yield word + (" " if i < len(words) - 1 else "")
    
    def _call_llm_api(self, prompt: str, stream: bool = False) -> Any:
        """
        Internal method to call LLM API.
        
        Args:
            prompt: The prompt to send
            stream: Whether to stream the response
            
        Returns:
            Response from LLM API
        """
        # This is a placeholder for actual LLM API call
        # In production, this would use OpenAI's streaming API or similar
        if stream:
            return self.stream_llm_response(prompt)
        else:
            return self.query_llm(prompt)
    
    def _create_request(self, prompt: str, stream: bool = False) -> urllib.request.Request:
        """Create HTTP request for LLM API."""
        url = f"{self.base_url}/chat/completions"
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {self.api_key}"
        }
        
        data = {
            "model": self.model,
            "messages": [{"role": "user", "content": prompt}],
            "stream": stream,
            "temperature": 0.7,
            "max_tokens": 1000
        }
        
        req = urllib.request.Request(
            url,
            data=json.dumps(data).encode("utf-8"),
            headers=headers,
            method="POST"
        )
        
        return req