"""Robot command definitions for trust layer.

All commands that can be issued by an operator or generated by the system
must be defined here as dataclasses with clear validation rules.

These commands flow through:
  1. nl_command_gateway (natural language → structured command)
  2. trust_edge (L2b) – adds context, trust budget
  3. safety_edge (L1) – deterministic validation
  4. robot_bridge – actuation
"""
from __future__ import annotations

import enum
import uuid
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple, Any


class CommandType(enum.Enum):
    """Generic command type identifiers used for capability mapping."""
    MOVE = "move"
    TURN = "turn"
    STOP = "stop"
    GRASP = "grasp"
    RELEASE = "release"
    LIFT = "lift"
    LOWER = "lower"
    CUT = "cut"
    WELD = "weld"
    SENSE = "sense"
    COMMUNICATE = "communicate"


@dataclass
class RobotCommand:
    """Base class for all robot commands."""
    command_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    robot_id: str = ""
    timestamp_ms: int = 0
    source: str = ""  # "operator", "autonomous", "system"
    priority: int = 0  # 0=lowest, 10=highest
    type: Optional["CommandType"] = None  # generic command type for capability checks
    params: Dict[str, Any] = field(default_factory=dict)  # command parameters
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "command_id": self.command_id,
            "robot_id": self.robot_id,
            "timestamp_ms": self.timestamp_ms,
            "source": self.source,
            "priority": self.priority,
            "command_type": self.__class__.__name__,
        }


@dataclass
class NavigateCommand(RobotCommand):
    """Command to navigate to a specific position."""
    target_x: float = 0.0
    target_y: float = 0.0
    target_yaw: float = 0.0
    max_speed_mps: float = 0.5
    obstacle_avoidance: bool = True
    
    def to_dict(self) -> Dict[str, Any]:
        base = super().to_dict()
        base.update({
            "target_x": self.target_x,
            "target_y": self.target_y,
            "target_yaw": self.target_yaw,
            "max_speed_mps": self.max_speed_mps,
            "obstacle_avoidance": self.obstacle_avoidance,
        })
        return base


@dataclass
class LookAtCommand(RobotCommand):
    """Command to look at a specific point or object."""
    target_x: float = 0.0
    target_y: float = 0.0
    target_z: float = 1.0
    duration_sec: float = 5.0
    
    def to_dict(self) -> Dict[str, Any]:
        base = super().to_dict()
        base.update({
            "target_x": self.target_x,
            "target_y": self.target_y,
            "target_z": self.target_z,
            "duration_sec": self.duration_sec,
        })
        return base


@dataclass
class TrackingCommand(RobotCommand):
    """Command to track an object based on textual description with periodic VLM verification.
    
    Flow:
    1. Operator gives text description: "следи за человеком в синей куртке"
    2. L2b (trust_edge) parses text → creates TrackingCommand
    3. L1 (safety_edge) validates parameters
    4. perception_edge initializes tracking using VLM
    5. Periodic verification runs to confirm object identity
    6. If object lost > max_lost_frames, system enters ADVISORY mode
    """
    object_description: str = ""  # Text description of object to track
    tracking_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    verification_interval_sec: float = 5.0  # Interval between VLM re-checks
    max_lost_frames: int = 3  # Maximum frames without detection before fail-safe
    safe_zones: List[str] = field(default_factory=list)  # Allowed zones for tracking
    require_continuous_tracking: bool = True  # If False, allow brief losses
    confidence_threshold: float = 0.7  # Minimum VLM confidence to accept match
    
    def to_dict(self) -> Dict[str, Any]:
        base = super().to_dict()
        base.update({
            "object_description": self.object_description,
            "tracking_id": self.tracking_id,
            "verification_interval_sec": self.verification_interval_sec,
            "max_lost_frames": self.max_lost_frames,
            "safe_zones": self.safe_zones,
            "require_continuous_tracking": self.require_continuous_tracking,
            "confidence_threshold": self.confidence_threshold,
        })
        return base


@dataclass
class StopCommand(RobotCommand):
    """Command to stop all movement immediately."""
    emergency_stop: bool = False
    reason: str = ""
    
    def to_dict(self) -> Dict[str, Any]:
        base = super().to_dict()
        base.update({
            "emergency_stop": self.emergency_stop,
            "reason": self.reason,
        })
        return base


@dataclass
class ScanAreaCommand(RobotCommand):
    """Command to scan an area by rotating or moving in a pattern."""
    center_x: float = 0.0
    center_y: float = 0.0
    radius_m: float = 2.0
    pattern: str = "circle"  # "circle", "spiral", "back_forth"
    duration_sec: float = 10.0
    
    def to_dict(self) -> Dict[str, Any]:
        base = super().to_dict()
        base.update({
            "center_x": self.center_x,
            "center_y": self.center_y,
            "radius_m": self.radius_m,
            "pattern": self.pattern,
            "duration_sec": self.duration_sec,
        })
        return base


def command_from_dict(data: Dict[str, Any]) -> Optional[RobotCommand]:
    """Factory function to create a command from a dictionary."""
    cmd_type = data.get("command_type", "")
    
    if cmd_type == "NavigateCommand":
        return NavigateCommand(
            command_id=data.get("command_id", str(uuid.uuid4())),
            robot_id=data.get("robot_id", ""),
            timestamp_ms=data.get("timestamp_ms", 0),
            source=data.get("source", ""),
            priority=data.get("priority", 0),
            target_x=data.get("target_x", 0.0),
            target_y=data.get("target_y", 0.0),
            target_yaw=data.get("target_yaw", 0.0),
            max_speed_mps=data.get("max_speed_mps", 0.5),
            obstacle_avoidance=data.get("obstacle_avoidance", True),
        )
    elif cmd_type == "LookAtCommand":
        return LookAtCommand(
            command_id=data.get("command_id", str(uuid.uuid4())),
            robot_id=data.get("robot_id", ""),
            timestamp_ms=data.get("timestamp_ms", 0),
            source=data.get("source", ""),
            priority=data.get("priority", 0),
            target_x=data.get("target_x", 0.0),
            target_y=data.get("target_y", 0.0),
            target_z=data.get("target_z", 1.0),
            duration_sec=data.get("duration_sec", 5.0),
        )
    elif cmd_type == "TrackingCommand":
        return TrackingCommand(
            command_id=data.get("command_id", str(uuid.uuid4())),
            robot_id=data.get("robot_id", ""),
            timestamp_ms=data.get("timestamp_ms", 0),
            source=data.get("source", ""),
            priority=data.get("priority", 0),
            object_description=data.get("object_description", ""),
            tracking_id=data.get("tracking_id", str(uuid.uuid4())),
            verification_interval_sec=data.get("verification_interval_sec", 5.0),
            max_lost_frames=data.get("max_lost_frames", 3),
            safe_zones=data.get("safe_zones", []),
            require_continuous_tracking=data.get("require_continuous_tracking", True),
            confidence_threshold=data.get("confidence_threshold", 0.7),
        )
    elif cmd_type == "StopCommand":
        return StopCommand(
            command_id=data.get("command_id", str(uuid.uuid4())),
            robot_id=data.get("robot_id", ""),
            timestamp_ms=data.get("timestamp_ms", 0),
            source=data.get("source", ""),
            priority=data.get("priority", 0),
            emergency_stop=data.get("emergency_stop", False),
            reason=data.get("reason", ""),
        )
    elif cmd_type == "ScanAreaCommand":
        return ScanAreaCommand(
            command_id=data.get("command_id", str(uuid.uuid4())),
            robot_id=data.get("robot_id", ""),
            timestamp_ms=data.get("timestamp_ms", 0),
            source=data.get("source", ""),
            priority=data.get("priority", 0),
            center_x=data.get("center_x", 0.0),
            center_y=data.get("center_y", 0.0),
            radius_m=data.get("radius_m", 2.0),
            pattern=data.get("pattern", "circle"),
            duration_sec=data.get("duration_sec", 10.0),
        )
    
    return None